Net Reproductive Rate
ihmeuw-demographics/demCore pull request #59
Opened 2020-09-01 18:58 UTC by krpaulson

## Describe changes

Add function to calculate net reproductive rate.

## What issues are related

Related to #19 

## Checklist

### Packages Repositories

* [ ] Have you read the [contributing guidelines](https://github.com/ihmeuw-demographics/packageTemplate/wiki#guide-to-r-package-development) for `ihmeuw-demographics` R packages?
* [ ] Have you successfully run `devtools::check()` locally?
* [ ] Have you updated or added function (and vignette if applicable) documentation? Did you update the 'man' and 'NAMESPACE' files with `devtools::document()`?
* [ ] Have you added in tests for the changes included in the PR?
* [ ] Do the changes follow the `ihmeuw-demographics` [code style](https://github.com/ihmeuw-demographics/packageTemplate/wiki/Code-style-guide)?
* [ ] Do your changes need to be immediately included in a new build of [`docker-base`](https://github.com/ihmeuw-demographics/docker-base) or [`docker-internal`](https://github.com/ihmeuw-demographics/docker-internal)? If so follow directions in those repositories to rebuild and redeploy the images.

## Details of PR

This PR is not yet ready for review.

2020-09-08 18:38 UTC, chacalle commented on R/gen_nrr.R
> +#'   nLx = 4.9
Is this nLx for the entire reproductive age group? Is it more common this will be age-group specific?

2020-09-08 18:39 UTC, chacalle commented on R/gen_nrr.R
> +    unique(dt$sex) == "female",
Should use `identical` instead of `==` in case there are more than one

2020-09-08 18:47 UTC, spencerpease commented on R/gen_nrr.R
> +gen_nrr <- function(dt, id_cols, reproductive_age_start = 15, reproductive_age_end = 50) {
What is our convention regarding `gen_*`? Should this be modifying a data.table in-place?

2020-09-08 18:48 UTC, chacalle requested changes

2020-09-08 18:48 UTC, chacalle commented on R/gen_nrr.R
> +#' Then, calculate NRR: sum(asfr * prop_female * nLx) over age, by id columns.
These equations are helpful It might be useful to link to a description of nrr somewhere.

2020-09-08 18:48 UTC, chacalle commented on tests/testthat/test-gen_nrr.R
> +})
Should eventually add in some basic tests for common errors that should be caught by the assertions.

2020-09-08 18:48 UTC, chacalle commented on R/gen_nrr.R
> +#'   fertility rate (ASFR) and sex-ratio at birth (SRB) and
and nLx

2020-09-08 18:48 UTC, chacalle commented on R/gen_nrr.R
> +gen_nrr <- function(dt, id_cols, reproductive_age_start = 15, reproductive_age_end = 50) {
The `gen_` functions should be reserved for modifying in place. Should this be `nrr_from_nFx_srb_nLx` to be consistent with our lifetable functions?

2021-02-16 17:54 UTC, erinamay submitted a review, later dismissed

2021-02-16 17:54 UTC, erinamay commented on R/calculate_nrr.R
> +
Should there also be checks for reasonable values (i.e. non negative?) of SRB/asfr/nLx and non-NAs?

2021-02-16 17:54 UTC, erinamay commented on R/calculate_nrr.R
> +    list(nrr = sum(asfr * prop_female * nLx)),
Should na.rm = TRUE be added, or no?

2021-02-22 17:09 UTC, chacalle approved these changes

2021-02-22 17:09 UTC, chacalle commented on R/calculate_nrr.R
> +                          reproductive_age_start = 15,
Should we make these defaults equal to the entire gbd reproductive age span?

2021-02-22 18:30 UTC, krpaulson commented on R/calculate_nrr.R
> +                          reproductive_age_start = 15,
Is that 10-60?

2021-02-22 18:31 UTC, krpaulson commented on R/calculate_nrr.R
> +    list(nrr = sum(asfr * prop_female * nLx)),
Not if we're requiring asfr, prop_female, and nLx to be non-NA

2021-02-22 18:31 UTC, chacalle commented on R/calculate_nrr.R
> +                          reproductive_age_start = 15,
10-55

2021-07-15 16:56 UTC, merged